# -*- coding: utf-8 -*-
"""task3ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPyiSLyhIg8UdzZ06_HMllz8fDOT6NY7
"""

# 📦 Install necessary libraries

# 📚 Imports
from transformers import pipeline
import gradio as gr

# 🔄 Load all models
sentiment_pipeline = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")
ner_pipeline = pipeline("ner", grouped_entities=True, model="dslim/bert-base-NER")

# Translation models
translator_tamil = pipeline("translation", model="Helsinki-NLP/opus-mt-en-mul")  # multilingual (need >>tam<<)
translator_hindi = pipeline("translation", model="Helsinki-NLP/opus-mt-en-hi")
translator_french = pipeline("translation", model="Helsinki-NLP/opus-mt-en-fr")

# 🎯 NLP Function for UI
def nlp_ui(text):
    # 1️⃣ Sentiment Analysis
    sent = sentiment_pipeline(text)[0]
    sentiment_result = f"{sent['label']} ({sent['score']:.2f})"

    # 2️⃣ Named Entity Recognition
    ner = ner_pipeline(text)
    ner_result = ", ".join([f"{e['entity_group']}({e['word']})" for e in ner])

    # 3️⃣ Translations (Tamil requires language tag!)
    tamil_input = f">>tam<< {text}"
    tamil_output = translator_tamil(tamil_input, max_length=512)[0]['translation_text'].strip()
    hindi_output = translator_hindi(text, max_length=512)[0]['translation_text'].strip()
    french_output = translator_french(text, max_length=512)[0]['translation_text'].strip()

    return sentiment_result, ner_result, tamil_output, hindi_output, french_output

# 🚀 Gradio UI
gr.Interface(
    fn=nlp_ui,
    inputs=gr.Textbox(lines=4, placeholder="Enter a sentence here..."),
    outputs=[
        gr.Textbox(label="Sentiment"),
        gr.Textbox(label="Named Entities"),
        gr.Textbox(label="Tamil Translation"),
        gr.Textbox(label="Hindi Translation"),
        gr.Textbox(label="French Translation")
    ],
    title="🧠 Mini NLP AI Assistant",
    description="Performs Sentiment Analysis, Named Entity Recognition, and Translation (Tamil, Hindi, French)."
).launch()